tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3a3939",
        "outline": "#948e9e",
        "primary-fixed-dim": "#cfbcff",
        "on-primary-fixed-variant": "#5229a9",
        "on-secondary-fixed": "#201340",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#ef9561",
        "on-tertiary": "#542200",
        "surface-container": "#201f1f",
        "inverse-primary": "#6a45c2",
        "error-container": "#93000a",
        "background": "#131313",
        "on-surface-variant": "#cbc3d5",
        "surface-dim": "#131313",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed": "#ffdbca",
        "secondary": "#cebef6",
        "surface": "#131313",
        "on-primary": "#3b0092",
        "primary-container": "#4a1fa1",
        "on-error": "#690005",
        "on-primary-container": "#b69bff",
        "outline-variant": "#494453",
        "on-tertiary-fixed": "#331200",
        "on-surface": "#e5e2e1",
        "surface-container-highest": "#353534",
        "inverse-surface": "#e5e2e1",
        "tertiary-container": "#6b2d00",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#22005c",
        "tertiary-fixed-dim": "#ffb68e",
        "on-tertiary-fixed-variant": "#753406",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#bdade3",
        "secondary-container": "#4c3f6e",
        "secondary-fixed-dim": "#cebef6",
        "on-secondary": "#352956",
        "on-secondary-fixed-variant": "#4c3f6e",
        "surface-tint": "#cfbcff",
        "inverse-on-surface": "#313030",
        "surface-variant": "#353534",
        "tertiary": "#ffb68e",
        "secondary-fixed": "#e9ddff",
        "error": "#ffb4ab",
        "primary-fixed": "#e9ddff",
        "surface-container-low": "#1c1b1b",
        "primary": "#cfbcff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
};
